import logging
from typing import Dict, Any, Optional
from pathlib import Path
import json

logger = logging.getLogger(__name__)


TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "en": {
        "city": "City",
        "country": "Country",
        "latitude": "Latitude",
        "longitude": "Longitude",
        "coordinates": "Coordinates",
        "theme": "Theme",
        "output": "Output",
        "format": "Format",
        "size": "Size",
        "generated_by": "Generated by MapToPoster",
        "searching_location": "Searching for location...",
        "fetching_data": "Fetching map data...",
        "rendering_map": "Rendering map...",
        "generating_poster": "Generating poster...",
        "saving_file": "Saving file...",
        "success": "Success!",
        "error": "Error",
        "location_not_found": "Location not found",
        "no_map_data": "No map data available",
        "invalid_coordinates": "Invalid coordinates",
        "dark_theme": "Dark",
        "blueprint_theme": "Blueprint",
        "neon_theme": "Neon Cyberpunk",
        "minimal_theme": "Minimal Light",
        "retro_theme": "Retro",
        "input_city": "Enter city name or coordinates",
        "select_theme": "Select theme",
        "select_format": "Select output format",
        "width": "Width",
        "height": "Height",
        "dpi": "DPI",
        "show_coordinates": "Show coordinates",
        "show_border": "Show border",
        "gradient_overlay": "Gradient overlay",
        "margin": "Margin",
        "cache_enabled": "Cache enabled",
        "cache_cleared": "Cache cleared",
        "help": "Help",
        "version": "Version",
        "about": "About",
    },
    "zh": {
        "city": "城市",
        "country": "国家",
        "latitude": "纬度",
        "longitude": "经度",
        "coordinates": "坐标",
        "theme": "主题",
        "output": "输出",
        "format": "格式",
        "size": "尺寸",
        "generated_by": "由 MapToPoster 生成",
        "searching_location": "正在搜索位置...",
        "fetching_data": "正在获取地图数据...",
        "rendering_map": "正在渲染地图...",
        "generating_poster": "正在生成海报...",
        "saving_file": "正在保存文件...",
        "success": "成功！",
        "error": "错误",
        "location_not_found": "未找到位置",
        "no_map_data": "无可用地图数据",
        "invalid_coordinates": "无效的坐标",
        "dark_theme": "深色",
        "blueprint_theme": "蓝图",
        "neon_theme": "霓虹赛博朋克",
        "minimal_theme": "极简浅色",
        "retro_theme": "复古",
        "input_city": "输入城市名称或坐标",
        "select_theme": "选择主题",
        "select_format": "选择输出格式",
        "width": "宽度",
        "height": "高度",
        "dpi": "分辨率",
        "show_coordinates": "显示坐标",
        "show_border": "显示边框",
        "gradient_overlay": "渐变遮罩",
        "margin": "边距",
        "cache_enabled": "缓存已启用",
        "cache_cleared": "缓存已清除",
        "help": "帮助",
        "version": "版本",
        "about": "关于",
    },
    "ja": {
        "city": "都市",
        "country": "国",
        "latitude": "緯度",
        "longitude": "経度",
        "coordinates": "座標",
        "theme": "テーマ",
        "output": "出力",
        "format": "フォーマット",
        "size": "サイズ",
        "generated_by": "MapToPosterで生成",
        "searching_location": "位置を検索中...",
        "fetching_data": "地図データを取得中...",
        "rendering_map": "地図をレンダリング中...",
        "generating_poster": "ポスターを生成中...",
        "saving_file": "ファイルを保存中...",
        "success": "成功！",
        "error": "エラー",
        "location_not_found": "位置が見つかりません",
        "no_map_data": "地図データがありません",
        "invalid_coordinates": "無効な座標",
        "dark_theme": "ダーク",
        "blueprint_theme": "ブループリント",
        "neon_theme": "ネオンサイバーパンク",
        "minimal_theme": "ミニマルライト",
        "retro_theme": "レトロ",
        "input_city": "都市名または座標を入力",
        "select_theme": "テーマを選択",
        "select_format": "出力フォーマットを選択",
        "width": "幅",
        "height": "高さ",
        "dpi": "DPI",
        "show_coordinates": "座標を表示",
        "show_border": "境界線を表示",
        "gradient_overlay": "グラデーションオーバーレイ",
        "margin": "マージン",
        "cache_enabled": "キャッシュ有効",
        "cache_cleared": "キャッシュをクリアしました",
        "help": "ヘルプ",
        "version": "バージョン",
        "about": "について",
    },
    "ko": {
        "city": "도시",
        "country": "국가",
        "latitude": "위도",
        "longitude": "경도",
        "coordinates": "좌표",
        "theme": "테마",
        "output": "출력",
        "format": "형식",
        "size": "크기",
        "generated_by": "MapToPoster에서 생성",
        "searching_location": "위치 검색 중...",
        "fetching_data": "지도 데이터 가져오는 중...",
        "rendering_map": "지도 렌더링 중...",
        "generating_poster": "포스터 생성 중...",
        "saving_file": "파일 저장 중...",
        "success": "성공!",
        "error": "오류",
        "location_not_found": "위치를 찾을 수 없음",
        "no_map_data": "지도 데이터 없음",
        "invalid_coordinates": "잘못된 좌표",
        "dark_theme": "다크",
        "blueprint_theme": "블루프린트",
        "neon_theme": "네온 사이버펑크",
        "minimal_theme": "미니멀 라이트",
        "retro_theme": "레트로",
        "input_city": "도시 이름 또는 좌표 입력",
        "select_theme": "테마 선택",
        "select_format": "출력 형식 선택",
        "width": "너비",
        "height": "높이",
        "dpi": "DPI",
        "show_coordinates": "좌표 표시",
        "show_border": "테두리 표시",
        "gradient_overlay": "그라데이션 오버레이",
        "margin": "여백",
        "cache_enabled": "캐시 활성화됨",
        "cache_cleared": "캐시 지워짐",
        "help": "도움말",
        "version": "버전",
        "about": "정보",
    },
}


SUPPORTED_LANGUAGES = ["en", "zh", "ja", "ko"]


class I18nManager:
    def __init__(self, language: str = "zh", custom_dir: Optional[Path] = None):
        self._language = language
        self._custom_dir = custom_dir
        self._translations: Dict[str, Dict[str, str]] = {}
        
        self._load_translations()
    
    def _load_translations(self) -> None:
        self._translations = {}
        
        for lang in SUPPORTED_LANGUAGES:
            if lang in TRANSLATIONS:
                self._translations[lang] = TRANSLATIONS[lang].copy()
        
        if self._custom_dir:
            self._load_custom_translations()
    
    def _load_custom_translations(self) -> None:
        if not self._custom_dir or not self._custom_dir.exists():
            return
        
        for lang_file in self._custom_dir.glob("*.json"):
            lang = lang_file.stem
            try:
                with open(lang_file, "r", encoding="utf-8") as f:
                    custom_translations = json.load(f)
                
                if lang not in self._translations:
                    self._translations[lang] = {}
                
                self._translations[lang].update(custom_translations)
                logger.debug(f"Loaded custom translations for: {lang}")
                
            except Exception as e:
                logger.warning(f"Failed to load translations from {lang_file}: {e}")
    
    @property
    def language(self) -> str:
        return self._language
    
    @language.setter
    def language(self, value: str) -> None:
        if value in self._translations or value in SUPPORTED_LANGUAGES:
            self._language = value
        else:
            logger.warning(f"Language '{value}' not supported, using default: zh")
            self._language = "zh"
    
    def get(self, key: str, default: Optional[str] = None) -> str:
        translations = self._translations.get(self._language, {})
        
        if key in translations:
            return translations[key]
        
        if self._language != "en":
            en_translations = self._translations.get("en", {})
            if key in en_translations:
                return en_translations[key]
        
        return default if default is not None else key
    
    def __call__(self, key: str, default: Optional[str] = None) -> str:
        return self.get(key, default)
    
    def list_languages(self) -> list:
        return list(self._translations.keys())
    
    def add_translation(self, lang: str, key: str, value: str) -> None:
        if lang not in self._translations:
            self._translations[lang] = {}
        self._translations[lang][key] = value
    
    def format_coords(self, lat: float, lon: float) -> str:
        lat_dir = "N" if lat >= 0 else "S"
        lon_dir = "E" if lon >= 0 else "W"
        
        lat_deg = abs(int(lat))
        lat_min = abs((lat - int(lat)) * 60)
        lon_deg = abs(int(lon))
        lon_min = abs((lon - int(lon)) * 60)
        
        return f"{lat_deg}°{lat_min:.1f}'{lat_dir} {lon_deg}°{lon_min:.1f}'{lon_dir}"


def get_translation(key: str, language: str = "zh") -> str:
    manager = I18nManager(language)
    return manager.get(key)


def supported_languages() -> list:
    return SUPPORTED_LANGUAGES.copy()
